//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationWCF.MainService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/EmployeeServices")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpID {
            get {
                return this.EmpIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpIDField, value) != true)) {
                    this.EmpIDField = value;
                    this.RaisePropertyChanged("EmpID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MainService.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetData", ReplyAction="http://tempuri.org/IEmployeeService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetData", ReplyAction="http://tempuri.org/IEmployeeService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAllUser", ReplyAction="http://tempuri.org/IEmployeeService/GetAllUserResponse")]
        System.Data.DataSet GetAllUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAllUser", ReplyAction="http://tempuri.org/IEmployeeService/GetAllUserResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/Insert", ReplyAction="http://tempuri.org/IEmployeeService/InsertResponse")]
        int Insert(string _name, string _email, string _phone, string _gender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/Insert", ReplyAction="http://tempuri.org/IEmployeeService/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(string _name, string _email, string _phone, string _gender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AddEmployyeeRecord", ReplyAction="http://tempuri.org/IEmployeeService/AddEmployyeeRecordResponse")]
        string AddEmployyeeRecord(WebApplicationWCF.MainService.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AddEmployyeeRecord", ReplyAction="http://tempuri.org/IEmployeeService/AddEmployyeeRecordResponse")]
        System.Threading.Tasks.Task<string> AddEmployyeeRecordAsync(WebApplicationWCF.MainService.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeRecords", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeRecordsResponse")]
        System.Data.DataSet GetEmployeeRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeRecords", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeRecordsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeeRecordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/DeleteRecords", ReplyAction="http://tempuri.org/IEmployeeService/DeleteRecordsResponse")]
        string DeleteRecords(WebApplicationWCF.MainService.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/DeleteRecords", ReplyAction="http://tempuri.org/IEmployeeService/DeleteRecordsResponse")]
        System.Threading.Tasks.Task<string> DeleteRecordsAsync(WebApplicationWCF.MainService.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/SearchEmployeeRecord", ReplyAction="http://tempuri.org/IEmployeeService/SearchEmployeeRecordResponse")]
        System.Data.DataSet SearchEmployeeRecord(WebApplicationWCF.MainService.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/SearchEmployeeRecord", ReplyAction="http://tempuri.org/IEmployeeService/SearchEmployeeRecordResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchEmployeeRecordAsync(WebApplicationWCF.MainService.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/UpdateEmployeeContact", ReplyAction="http://tempuri.org/IEmployeeService/UpdateEmployeeContactResponse")]
        string UpdateEmployeeContact(WebApplicationWCF.MainService.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/UpdateEmployeeContact", ReplyAction="http://tempuri.org/IEmployeeService/UpdateEmployeeContactResponse")]
        System.Threading.Tasks.Task<string> UpdateEmployeeContactAsync(WebApplicationWCF.MainService.Employee emp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : WebApplicationWCF.MainService.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<WebApplicationWCF.MainService.IEmployeeService>, WebApplicationWCF.MainService.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Data.DataSet GetAllUser() {
            return base.Channel.GetAllUser();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllUserAsync() {
            return base.Channel.GetAllUserAsync();
        }
        
        public int Insert(string _name, string _email, string _phone, string _gender) {
            return base.Channel.Insert(_name, _email, _phone, _gender);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(string _name, string _email, string _phone, string _gender) {
            return base.Channel.InsertAsync(_name, _email, _phone, _gender);
        }
        
        public string AddEmployyeeRecord(WebApplicationWCF.MainService.Employee emp) {
            return base.Channel.AddEmployyeeRecord(emp);
        }
        
        public System.Threading.Tasks.Task<string> AddEmployyeeRecordAsync(WebApplicationWCF.MainService.Employee emp) {
            return base.Channel.AddEmployyeeRecordAsync(emp);
        }
        
        public System.Data.DataSet GetEmployeeRecords() {
            return base.Channel.GetEmployeeRecords();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeeRecordsAsync() {
            return base.Channel.GetEmployeeRecordsAsync();
        }
        
        public string DeleteRecords(WebApplicationWCF.MainService.Employee emp) {
            return base.Channel.DeleteRecords(emp);
        }
        
        public System.Threading.Tasks.Task<string> DeleteRecordsAsync(WebApplicationWCF.MainService.Employee emp) {
            return base.Channel.DeleteRecordsAsync(emp);
        }
        
        public System.Data.DataSet SearchEmployeeRecord(WebApplicationWCF.MainService.Employee emp) {
            return base.Channel.SearchEmployeeRecord(emp);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchEmployeeRecordAsync(WebApplicationWCF.MainService.Employee emp) {
            return base.Channel.SearchEmployeeRecordAsync(emp);
        }
        
        public string UpdateEmployeeContact(WebApplicationWCF.MainService.Employee emp) {
            return base.Channel.UpdateEmployeeContact(emp);
        }
        
        public System.Threading.Tasks.Task<string> UpdateEmployeeContactAsync(WebApplicationWCF.MainService.Employee emp) {
            return base.Channel.UpdateEmployeeContactAsync(emp);
        }
    }
}
